name: Run __main__.py daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 3:00 AM UTC every day
  workflow_dispatch:     # Optional: lets you run manually from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Match your local Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: python __main__.py
